# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache: packages

os:
  - linux

# libglpk-dev is needed because of DHARMa #166, used indirectly by CroptimizR, see https://github.com/florianhartig/DHARMa/issues/166
addons:
  apt:
    packages:
      - libglpk-dev

install:
  - sudo apt-get update
  - sudo apt-get -y install openjdk-8-jdk
  - sudo rm /usr/local/lib/jvm/openjdk11/bin/java
  - sudo rm /usr/bin/java
  - sudo ln -s /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java /usr/bin/java
  - j=`which java`
  - echo $j
  - echo "java path"
  - ls -al $j
  - echo "java -version"
  - java -version
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - echo "JAVA_HOME"
  - echo $JAVA_HOME
  - R -e 'install.packages("remotes");library(remotes);remotes::install_deps(dependencies = FALSE,upgrade="always")'

r_github_packages:
  - SticsRPacks/SticsOnR
  - SticsRPacks/CroptimizR
  - SticsRPacks/SticsRFiles

jdk:
  - openjdk8

warnings_are_errors: false
