# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get -y install openjdk-8-jdk

r_github_packages:
  - SticsRPacks/SticsRFiles
  - SticsRPacks/SticsOnR
  - SticsRPacks/CroptimizR

jdk:
  - openjdk8

before_script:
  - env
  - echo "java -version"
  - java -version
  - echo "JAVA_HOME"
  - echo $JAVA_HOME
  - echo "Java location"
  - which java
