# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux

r_github_packages:
  - SticsRPacks/SticsRFiles
  - SticsRPacks/SticsOnR
  - SticsRPacks/CroptimizR
