# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux

before_install:
  #- sudo apt-get remove openjdk-11-jdk
  - sudo apt-get update
  - sudo apt-get -y install openjdk-8-jdk
  #- sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  # - sudo update-alternatives --set java /usr/local/lib/jvm/openjdk8/bin/java
  - echo "java path ..."
  - ls -al /usr/bin/java
  - echo "java -version"
  - java -version
  - echo "JAVA_HOME"
  - echo $JAVA_HOME
  - echo "Java location"
  - which java

r_github_packages:
  - SticsRPacks/SticsRFiles
  - SticsRPacks/SticsOnR
  - SticsRPacks/CroptimizR

jdk:
  - openjdk8

